<% file_path = File.expand_path('.my.cnf', '~') %>
<% file = IO.readlines(file_path) %>
<% user = file[1].split[-1] %>
<% password = file[2].split[-1] %>
<% socket = file[3].split[-1] %>

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tpr_development
  pool: 5
  username: <%= user %>
  password: <%= password %>
  socket: <%= socket %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tpr_test
  pool: 5
  username: <%= user %>
  password: <%= password %>
  socket: <%= socket %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tpr_production
  pool: 5
  username: <%= user %>
  password: <%= password %>
  socket: <%= socket %>

